language: java
jdk:
  - openjdk8

jobs:
  allow_failures:
    - jdk: openjdk11

dist: xenial

cache:
  directories:
    - $HOME/.m2

install:
 - sudo pip install wheel ansible pycrypto
 - sudo add-apt-repository universe
 - sudo apt-get update
 - git clone https://github.com/icatproject-contrib/icat-ansible.git
 - cd icat-ansible
 - echo -e "[icat-client-dev-hosts]\nlocalhost ansible_connection=local" > hosts
 - echo -e "icattravispw" > vault_pass.txt
 - mv ../vault.yml ./group_vars/all
 - mv ../icat-client-dev-hosts.yml .
 - 'sed -i -e "s/^payara_user: \"glassfish\"/payara_user: \"travis\"/" ./group_vars/all/vars.yml'
 - ansible-playbook --vault-password-file ./vault_pass.txt --inventory ./hosts ./icat-client-dev-hosts.yml
 - cd ..
 
script: 'mvn -DserverUrl=https://localhost:8181 test -B'
