language: java
jdk:
  - openjdk8
  - openjdk11

dist: xenial

cache:
  directories:
    - $HOME/.m2

install:
 - pip install --user requests-toolbelt
 - pip install --user wheel
 - sudo apt-get update
 - sudo apt-get install -y ansible
 - git clone https://github.com/brunocanning/icat-ansible.git
 - echo -e "[icat-test-host]\nlocalhost ansible_connection=local" > hosts
 - ansible-playbook --inventory ./hosts icat-ansible/icat-test-hosts.yml
