language: java
jdk:
  - openjdk8
  - openjdk11

dist: xenial

cache:
  directories:
    - $HOME/.m2

install:
 - sudo pip install requests-toolbelt
 - sudo pip install wheel
 - sudo pip install ansible
 - sudo add-apt-repository universe
 - sudo apt-get update
 - git clone https://github.com/brunocanning/icat-ansible.git
 - echo -e "[icat-test-hosts]\nlocalhost ansible_connection=local" > hosts
 - echo -e $ANSIBLE_VAULT_PASSWORD > vault_pass.txt
 - ansible-playbook --vault-password-file ./vault_pass.txt --inventory ./hosts icat-ansible/icat-test-hosts.yml
