language: java
jdk:
  - openjdk8
  - openjdk11

dist: xenial

cache:
  directories:
    - $HOME/.m2

install:
 - java -version
 - echo $JAVA_HOME
 - sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
 - sudo pip install requests-toolbelt wheel ansible pycrypto
 - sudo add-apt-repository universe
 - sudo apt-get update
 - git clone -b icat-dev-install-role https://github.com/louise-davies/icat-ansible.git
 - echo -e "[icat-dev-base-hosts]\nlocalhost ansible_connection=local" > hosts
 - echo -e $ANSIBLE_VAULT_PASSWORD > vault_pass.txt
 - mv vault.yml icat-ansible/group_vars/all
 - 'sed -i -e "s/^payara_user: ''glassfish''/payara_user: ''travis''/" icat-ansible/group_vars/all/vars.yml'
 - ansible-playbook --vault-password-file ./vault_pass.txt --inventory ./hosts -vvv icat-ansible/icat-dev-base-hosts.yml

