language: java
jdk:
  - openjdk8
  - openjdk11

dist: xenial

cache:
  directories:
    - $HOME/.m2

install:
 - sudo pip install requests-toolbelt
 - sudo pip install wheel
 - sudo pip install ansible 
 - git clone https://github.com/brunocanning/icat-ansible.git
 - echo -e "[icat-test-hosts]\nlocalhost ansible_connection=local" > hosts
 - ansible-playbook --inventory ./hosts icat-ansible/icat-test-hosts.yml
