---
- hosts: icat_client_dev_hosts
  become: true
  vars_files:
    - 'group_vars/all/vars.yml'
  vars:
    icat_server_version: '4.11.0'
  roles:
    - role: common
    - role: java
    - role: mariadb
    - role: icatdb
    - role: payara
    - role: authn-simple
    - role: authn-db
    - role: icat-lucene
    - role: dev-common
    - role: icat-server
