name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_and_tests:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 8
            experimental: false
          - version: 11
            experimental: true

    steps:
      - name: Checkout icat-client
        uses: actions/checkout@v2

      # Setup Java & Python
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"
          architecture: x64

      # ICAT Ansible clone and install dependencies
      - name: Checkout icat-ansible
        uses: actions/checkout@v2
        with:
          repository: icatproject-contrib/icat-ansible
          path: icat-ansible
      - name: Install Ansible
        run: pip install -r icat-ansible/requirements.txt

      # Prep for running the playbook
      - name: Create Hosts File
        run: echo -e "[icat-client-dev-hosts]\nlocalhost ansible_connection=local" > icat-ansible/hosts
      - name: Prepare vault pass
        run: echo -e "icattravispw" > icat-ansible/vault_pass.txt
      - name: Move vault to directory it'll get detected by Ansible
        run: mv vault.yml icat-ansible/group_vars/all
      - name: Move Ansible Playbook to directory it'll get detected by Ansible
        run: mv icat-client-dev-hosts.yml icat-ansible
      - name: Replace default payara user with Actions user
        run: |
          sed -i -e "s/^payara_user: \"glassfish\"/payara_user: \"runner\"/" icat-ansible/group_vars/all/vars.yml

      # Create local instance of ICAT
      - name: Run ICAT Ansible Playbook
        run: |
          ansible-playbook icat-ansible/icat-client-dev-hosts.yml -i icat-ansible/hosts --vault-password-file icat-ansible/vault_pass.txt -vv

      - name: Run Build
        run: |
          pip install requests requests-toolbelt wheel
          mvn install -DskipTests

      - name: Run Tests
        run: mvn -DserverUrl=https://$(hostname -f):8181 test -B
