name: CI Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 8
            experimental: false
          - version: 11
            experimental: true

    steps:
      - name: Checkout ICAT Client
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'

      - name: Installation
        run: |
          sudo pip install wheel ansible pycrypto
          sudo add-apt-repository universe
          sudo apt-get update

      - name: Setup python2
        run: |
          sudo apt install python2
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2 get-pip.py
          sudo python2 -m pip install requests requests_toolbelt

      - name: Checkout ICAT Ansible
        uses: actions/checkout@v2
        with:
          repository: icatproject-contrib/icat-ansible
          path: icat-ansible
          ref: underscore_changes
      
      - name: Setup Ansible
        run: |
          cd icat-ansible
          echo -e "[icat_client_dev_hosts]\nlocalhost ansible_connection=local" > hosts
          echo -e "icattravispw" > vault_pass.txt
          mv ../vault.yml ./group_vars/all
          mv ../icat_client_dev_hosts.yml .
          sed -i -e "s/^payara_user: \"glassfish\"/payara_user: \"runner\"/" ./group_vars/all/vars.yml
          sed -i -e "s/python-pip/python3-pip/" ./roles/dev_common/tasks/main.yml
          ansible-playbook --vault-password-file ./vault_pass.txt --inventory ./hosts ./icat_client_dev_hosts.yml
          cd ..

      - name: Test with Maven
        run: mvn -DserverUrl=https://$(hostname -f):8181 test -B
